/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { UserRole } from '../front.restapi.tmregis.model/UserRole';
import { HttpFile } from '../http/http';

export class JwtAuthResponse {
    /**
    * JWTで生成されたアクセストークン<br> ヘッダー.ペイロード.署名<br> で構成される 
    */
    'accessToken'?: string;
    /**
    * トークン種別<br> デフォルトでBearerを返却する 
    */
    'tokenType'?: string;
    'role'?: UserRole;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "accessToken",
            "baseName": "accessToken",
            "type": "string",
            "format": ""
        },
        {
            "name": "tokenType",
            "baseName": "tokenType",
            "type": "string",
            "format": ""
        },
        {
            "name": "role",
            "baseName": "role",
            "type": "UserRole",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return JwtAuthResponse.attributeTypeMap;
    }

    public constructor() {
    }
}



