/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { UserRole } from '../front.restapi.tmregis.model/UserRole';
import { HttpFile } from '../http/http';

/**
* ユーザー登録用Dto
*/
export class RegisterUserDto {
    /**
    * ユーザー名_姓
    */
    'lastName': string;
    /**
    * ユーザー名_名
    */
    'firstName': string;
    /**
    * メールアドレス
    */
    'email': string;
    /**
    * パスワード
    */
    'password': string;
    'role': UserRole;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "lastName",
            "baseName": "lastName",
            "type": "string",
            "format": ""
        },
        {
            "name": "firstName",
            "baseName": "firstName",
            "type": "string",
            "format": ""
        },
        {
            "name": "email",
            "baseName": "email",
            "type": "string",
            "format": ""
        },
        {
            "name": "password",
            "baseName": "password",
            "type": "string",
            "format": ""
        },
        {
            "name": "role",
            "baseName": "role",
            "type": "UserRole",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return RegisterUserDto.attributeTypeMap;
    }

    public constructor() {
    }
}



