/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Todoの詳細情報を格納するDto
*/
export class TodoReadDto {
    /**
    * UUID
    */
    'uuid'?: string;
    /**
    * Todoのタイトル
    */
    'title'?: string;
    /**
    * Todoの説明
    */
    'description'?: string;
    /**
    * Todoの完了状況
    */
    'completed'?: boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "uuid",
            "baseName": "uuid",
            "type": "string",
            "format": ""
        },
        {
            "name": "title",
            "baseName": "title",
            "type": "string",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "completed",
            "baseName": "completed",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return TodoReadDto.attributeTypeMap;
    }

    public constructor() {
    }
}

