/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { TodoReadRow } from '../front.restapi.tmtodo.model/TodoReadRow';
import { HttpFile } from '../http/http';

/**
* Todoのリストを格納するDto
*/
export class TodoReadDtoList {
    /**
    * Todoのリストを格納する配列
    */
    'dataList'?: Array<TodoReadRow>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "dataList",
            "baseName": "dataList",
            "type": "Array<TodoReadRow>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return TodoReadDtoList.attributeTypeMap;
    }

    public constructor() {
    }
}

