CREATE TABLE IF NOT EXISTS todo(
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    uuid VARCHAR(32) NOT NULL UNIQUE KEY,
    title VARCHAR(255) NOT NULL,
    description VARCHAR(255) NOT NULL,
    completed BOOLEAN NOT NULL DEFAULT false,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);