/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.2.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package net.ti.todo.tmtodo;

import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.annotation.Generated;
import jakarta.validation.Valid;
import jakarta.validation.constraints.Size;
import net.ti.todo.tmtodo.model.TodoReadDto;
import net.ti.todo.tmtodo.model.TodoReadDtoList;
import net.ti.todo.tmtodo.model.TodoRegistrationDto;
import net.ti.todo.tmtodo.model.TodoUpdateDto;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen")
@Validated
@Tag(name = "tmtodo", description = "ToDoを管理するAPI")
public interface TodosApi {

  /**
   * PUT /todos/{uuid}:complete : タスクを1件完了する [機能ID] TMTODO06
   *
   * @param uuid TodoUUID (required)
   * @return OK (status code 200)
   * or Not Found (status code 404)
   */
  @Operation(
    operationId = "completeTodoByUuid",
    summary = "タスクを1件完了する [機能ID] TMTODO06",
    tags = {"tmtodo"},
    responses = {
      @ApiResponse(responseCode = "200", description = "OK"),
      @ApiResponse(responseCode = "404", description = "Not Found")
    }
  )
  @RequestMapping(
    method = RequestMethod.PUT,
    value = "/todos/{uuid}:complete"
  )
  ResponseEntity<Void> completeTodoByUuid(
    @Size(min = 32, max = 32) @Parameter(name = "uuid", description = "TodoUUID", required = true, in = ParameterIn.PATH) @PathVariable("uuid") String uuid
  );


  /**
   * POST /todos : タスクを生成する [機能ID] TMTODO02
   *
   * @param todoRegistrationDto (optional)
   * @return OK (status code 200)
   */
  @Operation(
    operationId = "createTodo",
    summary = "タスクを生成する [機能ID] TMTODO02",
    tags = {"tmtodo"},
    responses = {
      @ApiResponse(responseCode = "200", description = "OK")
    }
  )
  @RequestMapping(
    method = RequestMethod.POST,
    value = "/todos",
    consumes = {"application/json"}
  )
  ResponseEntity<Void> createTodo(
    @Parameter(name = "TodoRegistrationDto", description = "") @Valid @RequestBody(required = false) TodoRegistrationDto todoRegistrationDto
  );


  /**
   * DELETE /todos/{uuid} : タスクを1件削除する [機能ID] TMTODO05
   *
   * @param uuid TodoUUID (required)
   * @return OK (status code 200)
   * or Not Found (status code 404)
   */
  @Operation(
    operationId = "deleteTodoByUuid",
    summary = "タスクを1件削除する [機能ID] TMTODO05",
    tags = {"tmtodo"},
    responses = {
      @ApiResponse(responseCode = "200", description = "OK"),
      @ApiResponse(responseCode = "404", description = "Not Found")
    }
  )
  @RequestMapping(
    method = RequestMethod.DELETE,
    value = "/todos/{uuid}"
  )
  ResponseEntity<Void> deleteTodoByUuid(
    @Size(min = 32, max = 32) @Parameter(name = "uuid", description = "TodoUUID", required = true, in = ParameterIn.PATH) @PathVariable("uuid") String uuid
  );


  /**
   * GET /todos/{uuid} : タスクを1件取得する [機能ID] TMTODO03
   *
   * @param uuid TodoUUID (required)
   * @return OK (status code 200)
   */
  @Operation(
    operationId = "getTodoByUuid",
    summary = "タスクを1件取得する [機能ID] TMTODO03",
    tags = {"tmtodo"},
    responses = {
      @ApiResponse(responseCode = "200", description = "OK", content = {
        @Content(mediaType = "application/json", schema = @Schema(implementation = TodoReadDto.class))
      })
    }
  )
  @RequestMapping(
    method = RequestMethod.GET,
    value = "/todos/{uuid}",
    produces = {"application/json"}
  )
  ResponseEntity<TodoReadDto> getTodoByUuid(
    @Size(min = 32, max = 32) @Parameter(name = "uuid", description = "TodoUUID", required = true, in = ParameterIn.PATH) @PathVariable("uuid") String uuid
  );


  /**
   * PUT /todos/{uuid}:incomplete : タスクを1件未完了にする [機能ID] TMTODO07
   *
   * @param uuid TodoUUID (required)
   * @return OK (status code 200)
   * or Not Found (status code 404)
   */
  @Operation(
    operationId = "incompleteTodoByUuid",
    summary = "タスクを1件未完了にする [機能ID] TMTODO07",
    tags = {"tmtodo"},
    responses = {
      @ApiResponse(responseCode = "200", description = "OK"),
      @ApiResponse(responseCode = "404", description = "Not Found")
    }
  )
  @RequestMapping(
    method = RequestMethod.PUT,
    value = "/todos/{uuid}:incomplete"
  )
  ResponseEntity<Void> incompleteTodoByUuid(
    @Size(min = 32, max = 32) @Parameter(name = "uuid", description = "TodoUUID", required = true, in = ParameterIn.PATH) @PathVariable("uuid") String uuid
  );


  /**
   * GET /todos : タスク一覧を取得する [機能ID] TMTODO01
   *
   * @return OK (status code 200)
   */
  @Operation(
    operationId = "listTodos",
    summary = "タスク一覧を取得する [機能ID] TMTODO01",
    tags = {"tmtodo"},
    responses = {
      @ApiResponse(responseCode = "200", description = "OK", content = {
        @Content(mediaType = "application/json", schema = @Schema(implementation = TodoReadDtoList.class))
      })
    }
  )
  @RequestMapping(
    method = RequestMethod.GET,
    value = "/todos",
    produces = {"application/json"}
  )
  ResponseEntity<TodoReadDtoList> listTodos(

  );


  /**
   * PUT /todos/{uuid} : タスクを1件更新する [機能ID] TMTODO04
   *
   * @param uuid          TodoUUID (required)
   * @param todoUpdateDto (optional)
   * @return OK (status code 200)
   */
  @Operation(
    operationId = "putTodoByUuid",
    summary = "タスクを1件更新する [機能ID] TMTODO04",
    tags = {"tmtodo"},
    responses = {
      @ApiResponse(responseCode = "200", description = "OK")
    }
  )
  @RequestMapping(
    method = RequestMethod.PUT,
    value = "/todos/{uuid}",
    consumes = {"application/json"}
  )
  ResponseEntity<Void> putTodoByUuid(
    @Size(min = 32, max = 32) @Parameter(name = "uuid", description = "TodoUUID", required = true, in = ParameterIn.PATH) @PathVariable("uuid") String uuid,
    @Parameter(name = "TodoUpdateDto", description = "") @Valid @RequestBody(required = false) TodoUpdateDto todoUpdateDto
  );

}
