/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.2.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package net.ti.todo.tmregis;

import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.annotation.Generated;
import jakarta.validation.Valid;
import net.ti.todo.common.ResponseSingleMessage;
import net.ti.todo.tmregis.model.JwtAuthResponse;
import net.ti.todo.tmregis.model.LoginDto;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen")
@Validated
@Tag(name = "tmregis", description = "ユーザー登録を管理するAPI")
public interface LoginApi {

  /**
   * POST /login : ログイン処理を実行する [機能ID] TMREGIS02
   *
   * @param loginDto (optional)
   * @return OK (status code 200)
   * or Bad Request (status code 400)
   */
  @Operation(
    operationId = "login",
    summary = "ログイン処理を実行する [機能ID] TMREGIS02",
    tags = {"tmregis"},
    responses = {
      @ApiResponse(responseCode = "200", description = "OK", content = {
        @Content(mediaType = "application/json", schema = @Schema(implementation = JwtAuthResponse.class))
      }),
      @ApiResponse(responseCode = "400", description = "Bad Request", content = {
        @Content(mediaType = "application/json", schema = @Schema(implementation = ResponseSingleMessage.class))
      })
    }
  )
  @RequestMapping(
    method = RequestMethod.POST,
    value = "/login",
    produces = {"application/json"},
    consumes = {"application/json"}
  )
  ResponseEntity<JwtAuthResponse> login(
    @Parameter(name = "LoginDto", description = "") @Valid @RequestBody(required = false) LoginDto loginDto
  );

}
