/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.2.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package net.ti.todo.tmregis;

import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.annotation.Generated;
import jakarta.validation.Valid;
import net.ti.todo.tmregis.model.RegisterUserDto;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen")
@Validated
@Tag(name = "tmregis", description = "ユーザー登録を管理するAPI")
public interface RegisterApi {

  /**
   * POST /register : ユーザー登録を実施する [機能ID] TMREGIS01
   *
   * @param registerUserDto (optional)
   * @return OK (status code 200)
   */
  @Operation(
    operationId = "createRegister",
    summary = "ユーザー登録を実施する [機能ID] TMREGIS01",
    tags = {"tmregis"},
    responses = {
      @ApiResponse(responseCode = "200", description = "OK")
    }
  )
  @RequestMapping(
    method = RequestMethod.POST,
    value = "/register",
    consumes = {"application/json"}
  )
  ResponseEntity<Void> createRegister(
    @Parameter(name = "RegisterUserDto", description = "") @Valid @RequestBody(required = false) RegisterUserDto registerUserDto
  );

}
