openapi: 3.0.3
info:
  title: "API"
  version: "1.0.0"
tags:
  - name: tmregis
    description: ユーザー登録を管理するAPI
paths:
  /login:
    post:
      operationId: login
      summary: ログイン処理を実行する [機能ID] TMREGIS02
      tags:
        - tmregis
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoginDto"
            # examples:
            #   description:
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/JwtAuthResponse"
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "./common/common.yml#/components/schemas/ResponseSingleMessage"
  /register:
    post:
      operationId: createRegister
      summary: ユーザー登録を実施する [機能ID] TMREGIS01
      tags:
        - tmregis
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RegisterUserDto"
      responses:
        "200":
          description: OK

components:
  schemas:
    LoginDto:
      type: object
      description: ログイン用Dto
      required:
        - userNameOrEmail
        - password
      properties:
        userNameOrEmail:
          description: ユーザー名またはメールアドレス
          type: string
          minLength: 6
          maxLength: 255
          example: sample@gmail.com
        password:
          description: パスワード
          type: string
          minLength: 8
          maxLength: 255
          example: password
    RegisterUserDto:
      type: object
      description: ユーザー登録用Dto
      required:
        - lastName
        - firstName
        - email
        - password
        - role
      properties:
        lastName:
          description: ユーザー名_姓
          type: string
          minLength: 1
          maxLength: 255
          example: 田中
        firstName:
          description: ユーザー名_名
          type: string
          minLength: 1
          maxLength: 255
          example: 太郎
        email:
          description: メールアドレス
          type: string
          x-field-extra-annotation: "@Pattern(regexp = \u0022^[a-zA-Z0-9!#$%&'*+\u005c\u005c/=?^_`{|}~-]+(\u005c\u005c.[a-zA-Z0-9!#$%&'*+\u005c\u005c/=?^_`{|}~-]+)*@[a-zA-Z0-9-]+(?:\u005c\u005c.[a-zA-Z0-9-]+)*$\u0022)"
          minLength: 6
          maxLength: 255
          example: sample@gmail.com
        password:
          description: パスワード
          type: string
          minLength: 8
          maxLength: 255
          example: password
        role:
          description: 権限
          type: string
          $ref: "./common/common.yml#/components/schemas/UserRole"
    JwtAuthResponse:
      type: object
      properties:
        accessToken:
          description: |
            JWTで生成されたアクセストークン<br>
            ヘッダー.ペイロード.署名<br>
            で構成される
          type: string
          example: xxxxxx.yyyyyy.zzzzzz
        tokenType:
          description: |
            トークン種別<br>
            デフォルトでBearerを返却する
          type: string
          default: Bearer
          example: Bearer
        role:
          description: 権限
          type: string
          $ref: "./common/common.yml#/components/schemas/UserRole"